service: chrome-feedback-with-lambda

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: eu-north-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.postsTableName}

custom:
  postsTableName: posts-table-${self:provider.stage}

plugins:
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin

functions:
  getPost:
    handler: app.getPost
    name: get-post
    memorySize: 128 
    timeout: 10
    events:
      - http:
          path: posts/{postId}
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:GetItem"
        Resource: !GetAtt PostsTable.Arn 

  createPost:
    handler: app.createPost
    name: create-post
    memorySize: 128 
    timeout: 10
    events:
      - http:
          path: posts
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:PutItem"
        Resource: !GetAtt PostsTable.Arn 

  updatePost:
    handler: app.updatePost
    name: update-post
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: posts/{postId}
          method: PUT
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:UpdateItem"
        Resource: !GetAtt PostsTable.Arn 

  deletePost:
    handler: app.deletePost
    name: delete-post
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: posts/{postId}
          method: DELETE
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:DeleteItem"
        Resource: !GetAtt PostsTable.Arn 

  getAllPosts:
    handler: app.getAllPosts
    name: get-all-posts
    memorySize: 128 
    timeout: 10
    events:
      - http:
          path: posts
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
        Resource: !GetAtt PostsTable.Arn 

resources:
  Resources:
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.postsTableName}
        AttributeDefinitions:
          - AttributeName: postId
            AttributeType: S
        KeySchema:
          - AttributeName: postId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1